name: pow-miner-opencl-release.yml

on:
  push:
    tags:
    - '*'

jobs:
  create-release:
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install OPENCL
      run: |
        sudo apt update -y && \
        sudo apt upgrade -y && \
        sudo apt install -y opencl-headers ocl-icd-opencl-dev

    - name: mkdir
      run: |
        mkdir build

    - name: cmake configuration
      run: |
        cd build && cmake -DTON_ARCH=x86-64 -DMINEROPENCL=1 -DCMAKE_BUILD_TYPE=Release ..

    - name: cmake build
      run: |
        cd build && cmake --build . --target pow-miner-opencl -j

    - name: naming convention
      run: |
        chmod +x build/crypto/pow-miner-opencl
        tar -zcf build/crypto/pow-miner-opencl-${{ matrix.os }}-x86-64.tar.gz build/crypto/pow-miner-opencl

    - name: packing
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: build/crypto/pow-miner-opencl-${{ matrix.os }}-x86-64.tar.gz
        token: ${{ secrets.GITHUB_TOKEN }}
